### ISSUE TITLE
Fantastic software! How do I get it to work with fasthttp?

### ISSUE THREAD

**Issue by hiqsociety** [efarrer/iothrottler#2]
given this example
https://github.com/valyala/fasthttp/blob/master/examples/helloworldserver/helloworldserver.go

how do i use the bandwidth throttling on it? 
possible to give an example per domain name bandwidth throtlling?

this will be extremely useful for everyone!

**Comment by hiqsociety** [comment]
How do you add iothrottler here?

import (
    "github.com/valyala/fasthttp"
)

var proxyClient = &fasthttp.HostClient{
    Addr: "upstream.host:port",
    // set other options here if required - most notably timeouts.
}

func ReverseProxyHandler(ctx *fasthttp.RequestCtx) {
    req := &ctx.Request
    resp := &ctx.Response
    prepareRequest(req)
    if err := proxyClient.Do(req, resp); err != nil {
        ctx.Logger().Printf("error when proxying the request: %s", err)
    }
    postprocessResponse(resp)
}

func prepareRequest(req *fasthttp.Request) {
    // do not proxy "Connection" header.
    req.Header.Del("Connection")
    // strip other unneeded headers.

    // alter other request params before sending them to upstream host
}

func postprocessResponse(resp *fasthttp.Response) {
    // do not proxy "Connection" header
    resp.Header.Del("Connection")

    // strip other unneeded headers

    // alter other response data if needed
}

func main() {
    if err := fasthttp.ListenAndServe(":8080", reverseProxyHandler); err != nil {
        log.Fatalf("error in fasthttp server: %s", err)
    }
}

**Comment by efarrer** [comment]
I'm not sure. It does appear that fasthttp.HostClient has a Dial member that returns a net.Conn. You could perhaps override that with your own Dial function that wraps the returned net.Conn with the IOThrottlerPool.AddConn.
